repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
    -   id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
    -   id: ruff-format
        types_or: [ python, pyi ]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
