# Generated by Django 5.1.1 on 2024-10-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_paymentsinputsmodel_ratesinputsmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsinputsmodel",
            name="inflation_adj",
            field=models.BooleanField(default=False),
        ),
    ]
