# Generated by Django 5.1.1 on 2024-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_paymentsinputsmodel_recurring_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsinputsmodel",
            name="recurring_length",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
