# Generated by Django 5.1.1 on 2024-11-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_remove_paymentsinputsmodel_recurring_purchase_inf_adj"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinputsmodel",
            name="add_healthcare",
            field=models.BooleanField(default=False),
        ),
    ]
