# Generated by Django 5.1.1 on 2025-01-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_generalinputsmodel_add_healthcare"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentsinputsmodel",
            name="monthly_pmt",
        ),
        migrations.AddField(
            model_name="paymentsinputsmodel",
            name="pmt_freq_mos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentsinputsmodel",
            name="reg_pmt_amt",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
