# Generated by Django 5.1.1 on 2025-01-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_remove_paymentsinputsmodel_monthly_pmt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentsinputsmodel",
            name="recurring_timeframe",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
