# Generated by Django 5.2 on 2025-10-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0012_remove_paymentsinputsmodel_inflation_adj_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="retirementinputsmodel",
            name="retirement_type",
            field=models.CharField(
                choices=[
                    ("traditional_401k", "Traditional 401(k)"),
                    ("roth_401k", "Roth 401(k)"),
                    ("traditional_ira", "Traditional IRA"),
                    ("roth_ira", "Roth IRA"),
                ],
                default="traditional_401k",
                max_length=20,
            ),
        ),
    ]
