# Generated by Django 5.2 on 2025-11-01 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0013_retirementinputsmodel_retirement_type"),
        ("pages", "move_retirement_extra_expenses"),
    ]

    operations = []
