# Generated by Django 5.2 on 2025-11-17 00:04

import pages.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0014_merge_20251101_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_extra_expenses",
            field=models.FloatField(
                default=0,
                validators=[
                    pages.model_validators.validate_retirement_extra_expenses,
                    pages.model_validators.decimal_validator,
                ],
            ),
        ),
    ]
