# Generated by Django 5.2 on 2026-03-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0015_alter_generalinputsmodel_retirement_extra_expenses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retirementinputsmodel",
            name="retirement_type",
            field=models.CharField(
                choices=[
                    ("traditional_401k", "Traditional 401(k)"),
                    ("roth_401k", "Roth 401(k)"),
                    ("traditional_ira", "Traditional IRA"),
                    ("roth_ira", "Roth IRA"),
                    ("hsa", "HSA"),
                    ("brokerage", "Brokerage"),
                ],
                default="traditional_401k",
                max_length=20,
            ),
        ),
    ]
