# Generated by Django 5.2 on 2026-04-12 16:29

from django.db import migrations, models


def set_standard_for_existing(apps, schema_editor):
    GeneralInputsModel = apps.get_model("pages", "GeneralInputsModel")
    GeneralInputsModel.objects.filter(medicare_coverage_type="none").update(
        medicare_coverage_type="standard"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0017_generalinputsmodel_medicare_coverage_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="medicare_coverage_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("standard", "Standard Medicare (Parts A, B, D)"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_standard_for_existing, migrations.RunPython.noop),
    ]
