# Generated by Django 6.0.4 on 2026-04-12 17:14

import pages.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_set_medicare_coverage_type_default_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinputsmodel',
            name='private_insurance_per_mo',
            field=models.FloatField(blank=True, default=None, null=True, validators=[pages.model_validators.decimal_validator]),
        ),
    ]
