# Generated by Django 5.0.1 on 2026-04-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_retirementinputsmodel_interest_rate_per_yr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retirementinputsmodel',
            name='inflation_adj',
            field=models.BooleanField(default=True, help_text='For pensions: whether the monthly payment is inflation-adjusted (COLA)'),
        ),
        migrations.AlterField(
            model_name='retirementinputsmodel',
            name='retirement_type',
            field=models.CharField(choices=[('traditional_401k', 'Traditional 401(k)'), ('roth_401k', 'Roth 401(k)'), ('traditional_ira', 'Traditional IRA'), ('roth_ira', 'Roth IRA'), ('hsa', 'HSA'), ('brokerage', 'Brokerage'), ('pension', 'Pension')], default='traditional_401k', max_length=20),
        ),
    ]
