# Generated by Django 5.0.1 on 2026-04-24 01:07

import pages.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0022_retirementinputsmodel_pension_and_inflation_adj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retirementinputsmodel",
            name="inflation_adj",
        ),
        migrations.AddField(
            model_name="retirementinputsmodel",
            name="pension_start_age_mos",
            field=models.IntegerField(
                blank=True,
                help_text="For pensions: age (months) when pension payments begin",
                null=True,
                validators=[pages.model_validators.validate_range_age_mos],
            ),
        ),
        migrations.AddField(
            model_name="retirementinputsmodel",
            name="pension_start_age_yrs",
            field=models.IntegerField(
                blank=True,
                help_text="For pensions: age (years) when pension payments begin",
                null=True,
                validators=[pages.model_validators.validate_range_age_yrs],
            ),
        ),
    ]
