# Generated by Django 5.2 on 2026-05-16 19:49

import pages.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0028_savingsinputsmodel_time_period_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_savings",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    pages.model_validators.validate_base_savings,
                    pages.model_validators.decimal_validator,
                ],
            ),
        ),
    ]
