# Generated by Django 4.2.7 on 2024-01-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputs", "0002_savingsinputsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentsInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("base_monthly_bills", models.FloatField()),
                (
                    "payment_item_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_item_pmt_start_age_yrs",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "payment_item_pmt_start_age_mos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "payment_item_pmt_length_yrs",
                    models.IntegerField(blank=True, null=True),
                ),
                ("payment_item_down_pmt", models.FloatField(blank=True, null=True)),
                ("payment_item_monthly_pmt", models.FloatField(blank=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_inputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payments_Inputs",
            },
        ),
    ]
