# Generated by Django 4.2.7 on 2024-01-06 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputs", "0003_paymentsinputsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetirementInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("base_retirement", models.FloatField()),
                ("base_retirement_per_mo", models.FloatField()),
                ("base_retirement_per_yr_increase", models.FloatField()),
                ("retirement_extra_expenses", models.FloatField()),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retirement_inputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Retirement_Inputs",
            },
        ),
        migrations.CreateModel(
            name="RatesInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("base_rf_interest_per_yr", models.FloatField()),
                ("base_mkt_interest_per_yr", models.FloatField()),
                ("rf_interest_change_mos", models.FloatField()),
                ("base_inflation_per_yr", models.FloatField()),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates_inputs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rates_Inputs",
            },
        ),
    ]
