# Generated by Django 4.2.7 on 2024-01-07 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputs", "0006_alter_savingsinputsmodel_base_monthly_bills"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="savings_inputs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
