# Generated by Django 4.2.7 on 2024-01-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0007_alter_savingsinputsmodel_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="savingsinputsmodel",
            name="savings_lower_limit",
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
