# Generated by Django 4.2.7 on 2024-01-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0008_savingsinputsmodel_savings_lower_limit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_down_pmt",
            new_name="down_pmt",
        ),
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_monthly_pmt",
            new_name="monthly_pmt",
        ),
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_pmt_length_yrs",
            new_name="pmt_length_yrs",
        ),
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_name",
            new_name="pmt_name",
        ),
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_pmt_start_age_mos",
            new_name="pmt_start_age_mos",
        ),
        migrations.RenameField(
            model_name="paymentsinputsmodel",
            old_name="payment_item_pmt_start_age_yrs",
            new_name="pmt_start_age_yrs",
        ),
    ]
