# Generated by Django 4.2.7 on 2024-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inputs",
            "0009_rename_payment_item_down_pmt_paymentsinputsmodel_down_pmt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentsinputsmodel",
            name="pmt_length_mos",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
