# Generated by Django 4.2.7 on 2024-01-13 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0010_paymentsinputsmodel_pmt_length_mos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ratesinputsmodel",
            name="rf_interest_change_mos",
        ),
    ]
