# Generated by Django 4.2.7 on 2024-01-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0011_remove_ratesinputsmodel_rf_interest_change_mos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalinputsmodel",
            old_name="birthday",
            new_name="birthdate",
        ),
    ]
