# Generated by Django 4.2.7 on 2024-02-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0012_rename_birthday_generalinputsmodel_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="birthdate",
            field=models.DateField(),
        ),
    ]
