# Generated by Django 4.2.7 on 2024-02-08 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0013_alter_generalinputsmodel_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_yrs",
            field=models.FloatField(
                validators=[
                    django.core.validators.MaxValueValidator(110, "That's too old!")
                ]
            ),
        ),
    ]
