# Generated by Django 4.2.7 on 2024-02-10 14:12

from django.db import migrations, models
import inputs.models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0017_alter_generalinputsmodel_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="birthdate",
            field=models.DateField(
                help_text="helper text",
                validators=[inputs.models.validate_range_birthdate],
            ),
        ),
    ]
