# Generated by Django 4.2.7 on 2024-02-10 14:16

from django.db import migrations, models
import inputs.models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0018_alter_generalinputsmodel_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="birthdate",
            field=models.DateField(
                help_text="Helper text for birthdate",
                validators=[inputs.models.validate_range_birthdate],
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="This determines whether or not these inputs will be used to calculate your financial situation",
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_mos",
            field=models.IntegerField(
                help_text="Helper text for retirement age months",
                validators=[inputs.models.validate_range_age_mos],
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_yrs",
            field=models.IntegerField(
                help_text="Helper text for retirement age years",
                validators=[inputs.models.validate_range_age_yrs],
            ),
        ),
    ]
