# Generated by Django 4.2.7 on 2024-02-10 19:43

from django.db import migrations, models
import inputs.models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0019_alter_generalinputsmodel_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="birthdate",
            field=models.DateField(
                help_text="Your birthdate (after 1900) in MM/DD/YYYY format",
                validators=[inputs.models.validate_range_birthdate],
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_mos",
            field=models.IntegerField(
                help_text="The age in months when you will retire. For example, if you are going to retire when you are 65 years and 3 months, this would be 3",
                validators=[inputs.models.validate_range_age_mos],
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_yrs",
            field=models.IntegerField(
                help_text="The age in years when you will retire. For example, if you are going to retire when you are 65 years and 3 months, put 65",
                validators=[inputs.models.validate_range_age_yrs],
            ),
        ),
    ]
