# Generated by Django 4.2.7 on 2024-02-11 01:59

from django.db import migrations, models
import inputs.models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0020_alter_generalinputsmodel_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_savings",
            field=models.FloatField(
                help_text='This is the amount of money you save each month and contribute to your savings account(s). A negative amount would represent you are spending that amount each month. If this is the case, it would probably be better to put a 0 in this field and move those payments to the "Payemnts" section',
                validators=[inputs.models.validate_base_savings],
            ),
        ),
    ]
