# Generated by Django 4.2.7 on 2024-02-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0022_alter_savingsinputsmodel_base_saved_per_mo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_saved_per_mo",
            field=models.FloatField(
                help_text="This is the average amount of money you save per month. Said another way, this is the average amount your savings account increases by each month (excluding interest). This could be negative."
            ),
        ),
    ]
