# Generated by Django 4.2.7 on 2024-02-16 01:19

from django.db import migrations, models
import inputs.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0023_alter_savingsinputsmodel_base_saved_per_mo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="birthdate",
            field=models.DateField(
                validators=[inputs.model_validators.validate_range_birthdate]
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_mos",
            field=models.IntegerField(
                validators=[inputs.model_validators.validate_range_age_mos]
            ),
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_yrs",
            field=models.IntegerField(
                validators=[inputs.model_validators.validate_range_age_yrs]
            ),
        ),
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_saved_per_mo",
            field=models.FloatField(
                help_text="This is the average amount of money you save per month. Said another way, this is the average amount your savings account increases by each month (excluding interest). This could be negative.",
                validators=[inputs.model_validators.validate_base_saved_per_mo],
            ),
        ),
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_savings_per_yr_increase",
            field=models.FloatField(
                help_text="The year-over-year savings increase (as a percent). For example, if you expect a 3% salary increase every year, you might put 3% here.",
                validators=[inputs.model_validators.validate_base_per_yr_increase],
            ),
        ),
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="This determines whether or not these inputs will be used to calculate your financial situation",
            ),
        ),
    ]
