# Generated by Django 4.2.7 on 2024-02-17 15:40

from django.db import migrations, models
import inputs.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0025_alter_paymentsinputsmodel_down_pmt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_savings",
            field=models.FloatField(
                validators=[
                    inputs.model_validators.validate_base_savings,
                    inputs.model_validators.decimal_validator,
                ]
            ),
        ),
    ]
