# Generated by Django 4.2.7 on 2024-02-17 15:49

import django.core.validators
from django.db import migrations, models
import inputs.model_validators


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0026_alter_savingsinputsmodel_base_savings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="retirement_age_yrs",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(110),
                    django.core.validators.MinValueValidator(0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="savingsinputsmodel",
            name="base_saved_per_mo",
            field=models.FloatField(
                validators=[
                    inputs.model_validators.validate_base_saved_per_mo,
                    inputs.model_validators.decimal_validator,
                ]
            ),
        ),
    ]
