var_descriptions = {
    "is_active": "This determines whether or not these inputs will be used to calculate your financial situation",
    "birthdate": "Your birthdate (after 1900) in MM/DD/YYYY format",
    "retirement_age_yrs": "The age in years when you will retire. For example, if you are going to retire when you are 65 years and 3 months, put 65",
    "retirement_age_mos": "The age in months when you will retire. For example, if you are going to retire when you are 65 years and 3 months, this would be 3",
    "add_healthcare": "Select this if you would like to have health care costs automatically included",
    "base_savings": "This is the amount of money you have in your savings account(s) right now",
    "base_saved_per_mo": 'This is the amount of money you save each month and contribute to your savings account(s). A negative amount would represent you are spending that amount each month. If this is the case, it would probably be better to put a 0 in this field and move those payments to the "Payemnts" section',
    "base_savings_per_yr_increase": "The year-over-year savings increase (as a percent). For example, if you expect a 3.0% salary increase every year, you might put 3.0% here.",
    "savings_lower_limit": "When you retire you will have options to withdraw from your savings, retirement, or both. This number is the lowest amount in your savings account (in today's dollars) until you fully withdraw from retirement",
    "base_monthly_bills": 'The amount of your average expenses every month. This should not include things that will end. For example, car payments or mortgage payments. Those should be input in the "Payments" section',
    "pmt_name": "The name of the payment. It's best to make these unique and descriptive",
    "pmt_start_age_yrs": "The age you are (in years) for when this payment will start. For example, if you think when you're 60 and 4 months you'll buy that Mustang you've always wanted, put 60 here",
    "pmt_start_age_mos": "The age you are (in months) for when this payment will start. For example, if you think when you're 60 and 4 months you'll buy that Mustang you've always wanted, put 4 here",
    "pmt_length_yrs": "How long (in years) you'll be paying for that new Mustang you buy when you're 60 and 4 months. Example: If your lease is for 3 years and 6 months, put 3 here",
    "pmt_length_mos": "How long (in months) you'll be paying for that new Mustang you buy when you're 60 and 4 months. Example: If your lease is for 3 years and 6 months, put 6 here",
    "down_pmt": "The down payment (if any) for this payment item. This does NOT include the first month's regular monthly payment",
    "reg_pmt_amt": "The monthly payment for this item. Example: You finance a TV for 12 months paying $100 a month. Put $100 here",
    "pmt_freq_mos": "The frequency of the payment (in months)",
    "base_retirement": "The amount of money you have in your retirement account(s) right now",
    "base_retirement_per_mo": "The amount of money that gets contributed to your retirement account each month. This includes all contribtuions, including employer contributions",
    "base_retirement_per_yr_increase": "If you plan to invest more money in your retirement account every year, put that year-over-year increase here (as dollars). Example: In the US, allowed contributions to your 401(k), HSA, etc generally increase every year. If you think they increase about $500 a year and you plan on maxxing them out every year, put $500 here",
    "retirement_extra_expenses": "This is the amount you believe you will spend in retirement that you aren't already spending now. Example: You don't travel much, but when you retire, plan on doing a nice trip every year. Maybe add $2,000 here to account for that",
    "base_rf_interest_per_yr": "This is the average interest rate you assume for your savings account(s). If you have more than one, take a weighted average",
    "base_mkt_interest_per_yr": "This is the average interest rate you assume for your retirement account(s). If you have more than one, take a weighted average",
    "base_inflation_per_yr": "This is the average inflation per year that you assume. 3.0% is pretty common",
}
