# Generated by Django 4.2.7 on 2023-12-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0002_testcalc_delete_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcalc",
            name="next_year",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
