# Generated by Django 4.2.7 on 2023-12-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0003_testcalc_next_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialInputs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.DateField()),
                ("base_retirement", models.FloatField()),
                ("base_retirement_per_mo", models.FloatField()),
                ("base_retirement_per_yr_increase", models.FloatField()),
                ("base_mkt_interest_per_yr", models.FloatField()),
                ("retirement_age_yrs", models.FloatField()),
                ("retirement_age_mos", models.FloatField()),
                ("base_rf_interest_per_yr", models.FloatField()),
                ("rf_interest_change_mos", models.FloatField()),
                ("ss_withdraw_age_yrs", models.FloatField()),
                ("ss_withdraw_age_mos", models.FloatField()),
                ("ss_withdraw_amt", models.FloatField()),
                ("base_savings", models.FloatField()),
                ("base_saved_per_mo", models.FloatField()),
                ("base_savings_per_yr_increase", models.FloatField()),
                ("base_monthly_bills", models.FloatField()),
                ("base_monthly_rent", models.FloatField()),
                ("savings_lower_limit", models.FloatField()),
                ("retirement_extra_expenses", models.FloatField()),
                ("payment_items", models.FloatField()),
                ("rent_end_age_yrs", models.FloatField()),
                ("rent_end_age_months", models.FloatField()),
            ],
        ),
    ]
