# Generated by Django 4.2.7 on 2023-12-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0004_financialinputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinputs",
            name="name",
            field=models.CharField(default="test", max_length=255),
        ),
    ]
