# Generated by Django 4.2.7 on 2023-12-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0007_financialinputs_input_dict"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialinputs",
            name="base_inflation_per_yr",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
