# Generated by Django 4.2.7 on 2023-12-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0008_financialinputs_base_inflation_per_yr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinputs",
            name="birthday",
            field=models.CharField(default="MM/DD/YYYY", max_length=10),
        ),
    ]
