# Generated by Django 4.2.7 on 2023-12-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0010_person_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_items",
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_down_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_monthly_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_pmt_length_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_pmt_start_age_mos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_1_item_pmt_start_age_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_down_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_monthly_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_pmt_length_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_pmt_start_age_mos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_2_item_pmt_start_age_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_down_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_monthly_pmt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_pmt_length_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_pmt_start_age_mos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="financialinputs",
            name="payment_3_item_pmt_start_age_yrs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialinputs",
            name="rent_end_age_months",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialinputs",
            name="rent_end_age_yrs",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
