# Generated by Django 4.2.7 on 2023-12-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0011_remove_financialinputs_payment_items_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinputs",
            name="input_dict",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
