# Generated by Django 4.2.7 on 2023-12-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0013_financialinputs_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialinputs",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
