# Generated by Django 4.2.7 on 2023-12-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0014_alter_financialinputs_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_down_pmt",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_monthly_pmt",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_name",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_pmt_length_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_pmt_start_age_mos",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_2_item_pmt_start_age_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_down_pmt",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_monthly_pmt",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_name",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_pmt_length_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_pmt_start_age_mos",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="payment_3_item_pmt_start_age_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="rent_end_age_months",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="rent_end_age_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="ss_withdraw_age_mos",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="ss_withdraw_age_yrs",
        ),
        migrations.RemoveField(
            model_name="financialinputs",
            name="ss_withdraw_amt",
        ),
    ]
