# Generated by Django 4.2.7 on 2023-12-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0016_remove_financialinputs_base_monthly_rent"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birthday", models.CharField(default="MM/DD/YYYY", max_length=10)),
                ("retirement_age_yrs", models.FloatField()),
                ("retirement_age_mos", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "General_Inputs",
            },
        ),
        migrations.DeleteModel(
            name="Job",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
