# Generated by Django 4.2.7 on 2023-12-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0017_generalinputsmodel_delete_job_delete_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavingsInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_savings", models.FloatField()),
                ("base_saved_per_mo", models.FloatField()),
                ("base_savings_per_yr_increase", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Savings_Inputs",
            },
        ),
    ]
