# Generated by Django 4.2.7 on 2023-12-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0018_savingsinputsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentsInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_monthly_bills", models.FloatField()),
                (
                    "payment_1_item_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_1_item_pmt_start_age_yrs",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "payment_1_item_pmt_start_age_mos",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "payment_1_item_pmt_length_yrs",
                    models.IntegerField(blank=True, null=True),
                ),
                ("payment_1_item_down_pmt", models.FloatField(blank=True, null=True)),
                (
                    "payment_1_item_monthly_pmt",
                    models.FloatField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Payments_Inputs",
            },
        ),
    ]
