# Generated by Django 4.2.7 on 2023-12-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0019_paymentsinputsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetirementInputsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base_retirement", models.FloatField()),
                ("base_retirement_per_mo", models.FloatField()),
                ("base_retirement_per_yr_increase", models.FloatField()),
                ("retirement_extra_expenses", models.FloatField()),
            ],
            options={
                "verbose_name_plural": "Retirement_Inputs",
            },
        ),
    ]
