# Generated by Django 4.2.7 on 2023-12-21 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0022_generalinputsmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
