# Generated by Django 4.2.7 on 2023-12-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0024_alter_generalinputsmodel_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="generalinputsmodel",
            old_name="created_at",
            new_name="modified_at",
        ),
    ]
