# Generated by Django 4.2.7 on 2023-12-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_situation",
            "0025_rename_created_at_generalinputsmodel_modified_at",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
