# Generated by Django 4.2.7 on 2023-12-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0029_alter_generalinputsmodel_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savingsinputsmodel",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="savingsinputsmodel",
            name="modified_at",
        ),
    ]
