# Generated by Django 4.2.7 on 2023-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0030_remove_savingsinputsmodel_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
