# Generated by Django 4.2.7 on 2023-12-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0031_alter_generalinputsmodel_modified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalinputsmodel",
            name="modified_at",
        ),
    ]
