# Generated by Django 4.2.7 on 2023-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0032_remove_generalinputsmodel_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinputsmodel",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
