# Generated by Django 4.2.7 on 2023-12-21 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("financial_situation", "0032_alter_generalinputsmodel_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalinputsmodel",
            name="modified_at",
        ),
        migrations.AlterField(
            model_name="generalinputsmodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="general_inputs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
