# Generated by Django 4.2.7 on 2023-12-22 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0033_generalinputsmodel_modified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalinputsmodel",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
