# Generated by Django 4.2.7 on 2024-01-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0036_paymentsinputsmodel_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GeneralInputsModel",
        ),
    ]
