# Generated by Django 4.2.7 on 2024-01-06 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0037_delete_generalinputsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SavingsInputsModel",
        ),
    ]
