# Generated by Django 4.2.7 on 2024-01-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0038_delete_savingsinputsmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentsInputsModel",
        ),
    ]
