# Generated by Django 4.2.7 on 2024-01-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("financial_situation", "0039_delete_paymentsinputsmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retirementinputsmodel",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="RatesInputsModel",
        ),
        migrations.DeleteModel(
            name="RetirementInputsModel",
        ),
    ]
