# Generated by Django 4.2.7 on 2024-01-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "financial_situation",
            "0040_remove_retirementinputsmodel_created_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialinputs",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="TestCalc",
        ),
        migrations.DeleteModel(
            name="FinancialInputs",
        ),
    ]
